---
- name: Setup | Debian | Ensure lib32(i386) is enabled.
  lineinfile:
    path: /var/lib/dpkg/arch
    regexp: "^i386"
    line: "i386"
    mode: "0644"
    create: true
  become: true
  when: setup_lib32 | bool

- name: Setup | Debian | Determine whether existing sources.list is managed by Ansible.
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    line: "# Managed by Ansible"
    state: present
  check_mode: true
  register: managed_res

- name: Setup | Debian | Setup apt sources
  ansible.builtin.template:
    src: apt-sources.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
    backup: "{{ managed_res.changed | bool | default(true) }}"
  become: true
  register: sources_res

- name: Setup | Debian | Ensure system is upgraded.
  ansible.builtin.apt:
    update_cache: true
    upgrade: "full"
  become: true
  register: dist_upgrade
  when: sources_res.changed | bool

- name: Setup | Debian | Ensure system is rebooted after dist upgrade.
  ansible.builtin.reboot:
    reboot_timeout: 1200
    connect_timeout: 60
  become: true
  register: reboot_res
  when: sources_res.changed | bool and
    dist_upgrade.changed | bool

- name: Setup | Debian | Fetch facts after successfull reboot.
  ansible.builtin.setup:
  when: reboot_res.rebooted is defined and
    reboot_res.rebooted | bool

- name: Setup | Debian | Ensure free firmware is installed.
  apt:
    name: firmware-linux-free
    state: present
  become: true
  when: install_firmware | bool

- name: Setup | Debian | Install non-free firmware.
  apt:
    name:
      - firmware-linux
      - firmware-linux-nonfree
    state: present
  become: true
  when: install_firmware_nonfree | bool and
    setup_repo_nonfreefirmware | bool

- name: Setup | Debian | Install misc firmware (non-free)
  apt:
    name: firmware-misc-nonfree
    state: present
  become: true
  when: install_firmware_misc | bool and
    setup_repo_nonfree | bool

- name: Setup | Debian | Build essential tools.
  become: true
  apt:
    name:
      - build-essential
      - dkms
      - gettext
      - "linux-headers-{{ ansible_kernel }}"
    state: present
  when: install_build_essentials | bool

- name: Setup | Debian | Package management tools.
  become: true
  apt:
    name:
      - aptitude
      - nala
      - software-properties-common
    state: present
