---
- name: Setup | Debian | Ensure lib32(i386) is enabled.
  lineinfile:
    path: /var/lib/dpkg/arch
    regexp: "^i386"
    line: "i386"
    mode: "0644"
    create: true
  become: true
  when: setup_lib32 | bool

- name: Setup | Debian | Determine whether existing sources.list is managed by Ansible.
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    line: "# Managed by Ansible"
    state: present
  check_mode: true
  register: managed_res

- name: Setup | Debian | Setup apt sources
  ansible.builtin.template:
    src: apt-sources.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
    backup: "{{ managed_res.changed | bool | default(true) }}"
  notify: Apt update

- name: Setup | Debian | Ensure firmware is installed.
  when: install_firmware | bool
  become: true
  apt:
    name: firmware-linux
    state: present

- name: Setup | Debian | Install non-free firmware.
  apt:
    name:
      - firmware-linux-nonfree
      - firmware-misc-nonfree
  become: true
  when: install_firmware_nonfree | bool

- name: Setup | Debian | Build essential tools.
  become: true
  apt:
    name:
      - build-essential
      - dkms
      - gettext
      - "linux-headers-{{ ansible_kernel }}"
    state: present
  when: install_build_essentials | bool

- name: Setup | Debian | Package management tools.
  become: true
  apt:
    name:
      - aptitude
      - nala
      - software-properties-common
    state: present
