- name: Devel | Ensure Clang is installed.
  package:
    state: present
    name:
      - clang
      - llvm
  when: install_clang | bool

- name: Devel | Setup python packages.
  import_tasks: ../packages/python.yml
  when: install_python | bool

- name: Devel | Setup rust environment
  import_tasks: ../packages/rust.yml
  when: install_rust | bool

- name: Devel | Ensure Go is installed.
  import_tasks: ../packages/golang.yml
  when: install_golang | bool

- name: Devel | Ensure ASDF is installed for managing versions.
  import_tasks: ../packages/asdf.yml
  when: install_asdf | bool
