---
- name: Users | Ensure default user group exist.
  group:
    name: "{{ default_user_group }}"
    state: present

- name: Users | Ensure user "{{ default_username }}" exists.
  user:
    state: present
    createhome: true
    name: "{{ default_user_username }}"
    group: "{{ default_user_group }}"
    groups: "ansible,{{ default_sudo_group }}"
    comment: "{{ default_user_fullname }}"
    password: "{{ default_user_passwd_hash }}"
    shell: "{{ default_user_shell }}"
