---
# tasks file for ansible-role-linux
- name: Load OS variable
  tags: always
  include_vars: "{{ ansible_distribution | title }}.yml"

- name: Setting up distro specific tasks.
  include_tasks: "setup/{{ ansible_distribution | title }}.yml"

- name: Install base packages.
  become: true
  import_tasks: packages/base.yml

- name: Setting up users.
  import_tasks: setup/Users.yml
  when: setup_users | bool
