---
# tasks file for ansible-role-linux
- name: Load OS variable
  tag: always
  include_vars: "{{ ansible_distribution | title }}.yml"

- name: Setting up distro specific tasks.
  include_tasks: "setup/{{ ansible_distribution | title }}.yml"

- name: Setting up users.
  import_tasks: setup/Users.yml
  when: setup_users | bool

- name: Install base packages.
  import_tasks: packages/base.yml

- name: Setting up Dev environment.
  import_tasks: setup/Devel.yml
  when: setup_dev_env | bool
