- name: Base | Ensure base packages are installed.
  package:
    state: present
    name:
      - bat
      - bc
      - btop
      - binutils
      - btop
      - "{{ build_tools_pkg }}"
      - colordiff
      - cifs-utils
      - curl
      - cronie
      - dialog
      - "{{ dns_utils_pkg }}"
      - git
      - gzip
      - lf
      - "{{ lm_sensors_pkg }}"
      - lsd
      - lsof
      - neofetch
      - nftables
      - net-tools
      - "{{ python_pkg }}"
      - "{{ python_pip_pkg }}"
      - "{{ nfs_client_pkg }}"
      - perl
      - pigz
      - p7zip
      - plocate
      - ruby
      - rsync
      - "{{ ruby_rake_pkg }}"
      - screen
      - sshfs
      - trash-cli
      - unrar
      - unzip
      - util-linux
      - vim
      - wget
      - whois
      - zoxide
      - zsh

- name: Base | Ensure unnecessary packages are removed.
  apt:
    state: absent
    name:
      - cowsay
      - exim4
      - exim4-base
      - exim4-config
      - nano
  when: ansible_distribution == "Debian"

- name: Base | Ensure man-page is installed (Arch).
  community.general.pacman:
    state: present
    name:
      - man-db
      - man-pages
  when: ansible_distribution == "Archlinux"
