- name: Base | Ensure base packages are installed.
  package:
    state: present
    name:
      - at
      - bat
      - btop
      - "{{ build_tools_pkg }}"
      - colordiff
      - curl
      - "{{ dns_utils_pkg }}"
      - btop
      - git
      - htop
      - lf
      - "{{ lm_sensors_pkg }}"
      - lsd
      - lsof
      - mc
      - neofetch
      - net-tools
      - "{{ python_pkg }}"
      - "{{ python_pip_pkg }}"
      - "{{ nfs_client_pkg }}"
      - perl
      - ruby
      - rsync
      - "{{ ruby_rake_pkg }}"
      - screen
      - sshfs
      - trash-cli
      - vim
      - wget
      - whois
      - zsh

- name: Base | Ensure unnecessary packages are removed.
  package:
    state: absent
    name:
      - cowsay
      - exim4
      - exim4-base
      - exim4-config
      - nano
    when: ansible_distribution == "Debian"

- name: Base | Ensure man-page is installed (Arch).
  community.general.pacman:
    state: present
    name:
      - man-db
      - man-pages
  when: ansible_distribution == "Archlinux"
