---
- name: Base | Ensure base packages are installed.
  package:
    state: present
    name:
      - bc
      - binutils
      - "{{ build_tools_pkg }}"
      - cmake
      - colordiff
      - cifs-utils
      - curl
      - "{{ cron_pkg }}"
      - dialog
      - "{{ dns_utils_pkg }}"
      - git
      - gzip
      - jq
      - lf
      - "{{ lm_sensors_pkg }}"
      - lsof
      - nftables
      - net-tools
      - "{{ python_pkg }}"
      - "{{ python_pip_pkg }}"
      - "{{ nfs_client_pkg }}"
      - perl
      - pigz
      - p7zip
      - plocate
      - ruby
      - rsync
      - "{{ ruby_rake_pkg }}"
      - screen
      - sshfs
      - unzip
      - util-linux
      - vim
      - wget
      - whois

- name: Base | Ensure unnecessary packages are removed.
  apt:
    state: absent
    name:
      - cowsay
      - exim4
      - exim4-base
      - exim4-config
      - nano
  when: ansible_distribution == "Debian"

- name: Base | Ensure man-page is installed (Arch).
  community.general.pacman:
    state: present
    name:
      - man-db
      - man-pages
  when: ansible_distribution == "Archlinux"

- name: Base | Ensure eza is installed (Arch) & Debian non stable.
  ansible.builtin.package:
    name: eza
    state: present
  when: install_base_extras and
    (ansible_distribution == "Archlinux" or
    ansible_distribution_release == "trixie")

- name: Base | Ensure eza is installed in Debian Stable (bookworm and earlier)
  when: install_base_extras and
    ansible_distribution == "Debian" and
    (ansible_distribution_release != "trixie" and
    ansible_distribution_major_version <= "12")
  block:
    - name: Apt | Ensure gierens repo signing key is added to apt.
      apt_key:
        url: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
        keyring: /etc/apt/keyrings/gierens.gpg
        state: present
    - name: Apt | Ensure gierens repo is added to /etc/apt/sources.list.
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main"
        state: present
    - name: Apt | Ensure eza is installed.
      apt:
        name: eza
        state: present

- name: Base | Ensure extra utilities are installed.
  when: install_base_extras | bool and
    ( ansible_distribution == "Archlinux" or
      ( ansible_distribution == "Debian" and setup_repo_nonfree ))
  package:
    state: present
    name:
      - bat
      - btop
      - cups
      - dosfstools
      - exfatprogs
      - gnupg
      - groff
      - imagemagick
      - magic-wormhole
      - neofetch
      - ntfs-3g
      - trash-cli
      - unrar
      - zoxide
      - zsh

- name: Base | Determine if cargo is installed.
  shell: "command -v cargo > /dev/null"
  become: false
  ignore_errors: true
  changed_when: false
  register: cmd_cargo_res

- name: Base | Ensure packages are installed via cargo.
  become: false
  when: cmd_cargo_res is defined and
    cmd_cargo_res.rc == 0
  community.general.cargo:
    state: present
    name:
      - cargo-update
      - keepass-diff
      - starship
      - zellij
